### ISSUE TITLE
No encuentro el link del manual

### ISSUE THREAD

**Issue by jcrucesdeveloper** [TaconeoMental/WaidLang#3]
Todo bien, pero no encuentro el manual. :)

**Comment by TaconeoMental** [comment]
La documentación es la última de mis prioridades por el momento, Jorge. Cuando el lenguaje ya funcione bien y sea utilizable escribiré documentación para que cualquier persona lo use.
Espero que ver los ejemplos te de una vaga idea de la sintaxis básica del lenguaje.
